target:
- target
continuous_cols:
- col_0
- col_1
- col_2
- col_3
- col_4
- col_5
- col_6
- col_7
- col_8
- col_9
- col_10
- col_11
- col_12
- col_13
- col_14
- col_15
- col_16
- col_17
- col_18
- col_19
- col_20
- col_21
- col_22
- col_23
- col_24
- col_25
- col_26
- col_27
- col_28
- col_29
- col_30
- col_31
- col_32
- col_33
- col_34
- col_35
- col_36
- col_37
- col_38
- col_39
- col_40
- col_41
- col_42
- col_43
- col_44
- col_45
- col_46
- col_47
- col_48
- col_49
- col_50
- col_51
- col_52
- col_53
- col_54
- col_55
- col_56
- col_57
- col_58
- col_59
- col_60
- col_61
- col_62
- col_63
- col_64
- col_65
- col_66
- col_67
- col_68
- col_69
- col_70
- col_71
- col_72
- col_73
- col_74
- col_75
- col_76
- col_77
- col_78
- col_79
- col_80
- col_81
- col_82
- col_83
- col_84
- col_85
- col_86
- col_87
- col_88
- col_89
- col_90
- col_91
- col_92
- col_93
- col_94
- col_95
- col_96
- col_97
- col_98
- col_99
- col_100
- col_101
- col_102
- col_103
- col_104
- col_105
- col_106
- col_107
- col_108
- col_109
- col_110
- col_111
- col_112
- col_113
- col_114
- col_115
- col_116
- col_117
- col_118
- col_119
- col_120
- col_121
- col_122
- col_123
- col_124
- col_125
- col_126
- col_127
- col_128
- col_129
- col_130
- col_131
- col_132
- col_133
- col_134
- col_135
- col_136
- col_137
- col_138
- col_139
- col_140
- col_141
- col_142
- col_143
- col_144
- col_145
- col_146
- col_147
- col_148
- col_149
- col_150
- col_151
- col_152
- col_153
- col_154
- col_155
- col_156
- col_157
- col_158
- col_159
- col_160
- col_161
- col_162
- col_163
- col_164
- col_165
- col_166
- col_167
- col_168
- col_169
- col_170
- col_171
- col_172
- col_173
- col_174
- col_175
- col_176
- col_177
- col_178
- col_179
- col_180
- col_181
- col_182
- col_183
- col_184
- col_185
- col_186
- col_187
- col_188
- col_189
- col_190
- col_191
- col_192
- col_193
- col_194
- col_195
- col_196
- col_197
- col_198
- col_199
- col_200
- col_201
- col_202
- col_203
- col_204
- col_205
- col_206
- col_207
- col_208
- col_209
- col_210
- col_211
- col_212
- col_213
- col_214
- col_215
- col_216
- col_217
- col_218
- col_219
- col_220
- col_221
- col_222
- col_223
- col_224
- col_225
- col_226
- col_227
- col_228
- col_229
- col_230
- col_231
- col_232
- col_233
- col_234
- col_235
- col_236
- col_237
- col_238
- col_239
- col_240
- col_241
- col_242
- col_243
- col_244
- col_245
- col_246
- col_247
- col_248
- col_249
- col_250
- col_251
- col_252
- col_253
- col_254
- col_255
- col_256
- col_257
- col_258
- col_259
- col_260
- col_261
- col_262
- col_263
- col_264
- col_265
- col_266
- col_267
- col_268
- col_269
- col_270
- col_271
- col_272
- col_273
- col_274
- col_275
- col_276
- col_277
- col_278
- col_279
- col_280
- col_281
- col_282
- col_283
- col_284
- col_285
- col_286
- col_287
- col_288
- col_289
- col_290
- col_291
- col_292
- col_293
- col_294
- col_295
- col_296
- col_297
- col_298
- col_299
- col_300
- col_301
- col_302
- col_303
- col_304
- col_305
- col_306
- col_307
- col_308
- col_309
- col_310
- col_311
- col_312
- col_313
- col_314
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
pickle_protocol: 2
dataloader_kwargs: {}
task: classification
head: LinearHead
head_config:
  layers: ''
embedding_dims: []
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: CrossEntropyLoss
metrics:
- accuracy
metrics_prob_input:
- false
metrics_params:
- sub_params_list:
  - task: multiclass
    num_classes: 2
    top_k: 1
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.node
_model_name: NODEModel
_backbone_name: NODEBackbone
_config_name: NodeConfig
num_layers: 2
num_trees: 256
additional_tree_output_dim: 3
depth: 4
choice_function: entmax15
bin_function: entmoid15
max_features: null
input_dropout: 0.0
initialize_response: normal
initialize_selection_logits: uniform
threshold_init_beta: 1.0
threshold_init_cutoff: 1.0
batch_size: 16
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 20
min_epochs: 1
max_time: null
accelerator: gpu
devices: 1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 5
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: simple
precision: '32'
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
lr_scheduler_interval: epoch
categorical_dim: 0
continuous_dim: 315
output_dim: 2
output_cardinality:
- 2
categorical_cardinality: []
embedded_cat_dim: 0
